
name: Rust

on:
  push:
    branches: [ main, ci-test ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_STABLE: stable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Cargo dependencies
        id: cache-cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust ${{ env.RUST_STABLE }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_STABLE }}
          override: true
      - name: Checking if there will be a cache hit
        run: |
          echo "Cache hit: ${{ steps.cache-cargo.outputs.cache-hit }}"
      - name: Install Rust
        run: rustup update stable
        working-directory: ./API
      - name: Build
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        run: cargo build --verbose -j 32
        working-directory: ./API
      - name: Check
        run: cargo check --verbose -j 32