name: Rust

on:
  push:
    paths:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/rust.yml'
    branches: [ main, ci-test ]
  pull_request:
    paths:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/rust.yml'
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Cargo dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust ${{ env.RUST_STABLE }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Show Context
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Install Rust
        run: rustup update nightly
        working-directory: ./API
      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo build --verbose
        working-directory: ./API
      - name: Check
        run: cargo check --verbose
        working-directory: ./API
