
name: Rust

on:
  push:
    branches: [ main, ci-test ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_STABLE: stable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable
        working-directory: ./API
      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo check --verbose
        working-directory: ./API
